version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_DB: agendamentos
      POSTGRES_USER: ultracar
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  spring:
    build: .
    container_name: spring_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agendamentos
      SPRING_DATASOURCE_USERNAME: ultracar
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
